CREATE DATABASE content CHARACTER SET utf8;
CREATE TABLE posts(userId INT NOT NULL,id INT NOT NULL PRIMARY KEY ,title VARCHAR(255),body VARCHAR(2500));
CREATE TABLE comments(postId INT NOT NULL,id INT NOT NULL PRIMARY KEY ,name VARCHAR(255),email VARCHAR(255),body VARCHAR(2500));